### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/bilingual_book_maker#192]
- [ ] batch
- [ ] free deepL
- [ ] try backoff
- [ ] output single book
- [ ] clean all PR issue
- [ ] MakeFile easy to test local

https://twitter.com/xuwenhao/status/1637340234244558849?s=20

**Comment by yihong0618** [comment]
PR welcome

**Comment by LonqXP** [comment]
Small question. Is it possible to disable the bilingual translation and leave only one language in the output file?

**Comment by yihong0618** [comment]
> Small question. Is it possible to disable the bilingual translation and leave only one language in the output file?

yes...in README

**Comment by LonqXP** [comment]
> > Small question. Is it possible to disable the bilingual translation and leave only one language in the output file?
> 
> yes...in README

Is it the --prompt? I can't seem to find the exact argument or descriptions to leave only the one output language in the README file

**Comment by yihong0618** [comment]
> > > Small question. Is it possible to disable the bilingual translation and leave only one language in the output file?
> > 
> > 
> > yes...in README
> 
> Is it the --prompt? I can't seem to find the exact argument or descriptions to leave only the one output language in the README file

--single_translate

**Comment by LonqXP** [comment]
> > > > Small question. Is it possible to disable the bilingual translation and leave only one language in the output file?
> > > 
> > > 
> > > yes...in README
> > 
> > Is it the --prompt? I can't seem to find the exact argument or descriptions to leave only the one output language in the README file
> 
> --single_translate
> 

Okay, thank you!

**Comment by lin16303** [comment]
是否可以增加支持本地部署大模型，ollama的api

**Comment by yihong0618** [comment]
> 是否可以增加支持本地部署大模型，ollama的api

我们稍后看看

**Comment by shawnzhou1120** [comment]
能否增加MD格式文件的支持，翻译后输出文档仍然保持MD的格式？
